apiVersion: v1
kind: Pod
metadata:
  name: deepfloydif
spec:
  restartPolicy: Never

  containers:
  - name: deep-floyd-if-container
    image: "registry.ferrari.snucse.org:30443/deep/tritonserver:v17"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 40
        memory: "120Gi"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: "/opt/tritonserver/pretrained_model"
      name: deep-floyd-if-pv
  volumes:
  - name: deep-floyd-if-pv
    persistentVolumeClaim:
      claimName: deep-floyd-if-pvc
  imagePullSecrets:
  - name: regcred