apiVersion: v1
kind: Pod
metadata:
  name: sd
spec:
  restartPolicy: Never

  containers:
  - name: deep-floyd-if-container
    image: "registry.ferrari.snucse.org:30443/deep/tritonserver:sdxl6"
    args: ["tritonserver","--model-repository","/opt/tritonserver/models"]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 50
        memory: "220Gi"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: "/opt/tritonserver/pretrained_model"
      name: deep-floyd-if-pv
  volumes:
  - name: deep-floyd-if-pv
    persistentVolumeClaim:
      claimName: deep-floyd-if-pvc
  imagePullSecrets:
  - name: regcred