apiVersion: v1
kind: Pod
metadata:
  name: spire
spec:
  restartPolicy: Never
  containers:
  - name: spire-container
    image: ""spire_ai:latest""
    command: ["/bin/sh","-c"]
    args:
      - cd /opt/tritonserver/pretrained_model;
        wget -N https://github.com/IDEA-Research/OpenSeeD/releases/download/openseed/model_state_dict_swint_51.2ap.pt;
        cd /opt/tritonserver/models/open_seed/1/Mask2Former/mask2former/modeling/pixel_decoder/ops;
        sh make.sh;
        cd /opt/tritonserver;
        tritonserver --model-repository=/opt/tritonserver/models
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 25
        memory: "110Gi"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: "/opt/tritonserver/pretrained_model"
      name: pretrained-model
  volumes:
  - name: pretrained-model
    hostPath:
      path: "/pretrained_model"
      type: DirectoryOrCreate
  imagePullSecrets:
  - name: regcred